### ISSUE TITLE
Bounds error getting pdf for last bin

### ISSUE THREAD

**Issue by JobJob** [oschulz/EmpiricalDistributions.jl#5]
```
using EmpiricalDistributions: UvBinnedDist
a = [1,2,3]
h = fit(Histogram, a)
uvd = UvBinnedDist(h)
pdf(uvd, 10)
```
Gives
```
BoundsError: attempt to access 3-element Array{Float64,1} at index [4]
getindex(::Array{Float64,1}, ::Int64) at array.jl:744
pdf(::UvBinnedDist{Float64}, ::Int64) at uv_binned_dist.jl:89
...
```
I noticed that `length(uvd.edges), length(uvd.volumes)` returns `4, 3`

I'm on StatsBase v0.32.2

**Comment by oschulz** [comment]
> I noticed that `length(uvd.edges), length(uvd.volumes)` returns `4, 3`

That is expected, it's a bit annoying, though. I've proposed to do this differently (JuliaStats/StatsBase.jl#514), but haven't implemented it yet.

> `pdf(uvd, 10)`
> BoundsError: attempt to access 3-element Array{Float64,1} at index [4]

That is current the expected behavior, since

    (minimum(uvd), maximum(uvd)) == (1.0, 4.0)

So `10` is outside of the support of `uvd`. The question is, what should happen outside of the support? Maybe it would indeed be better to return zero, instead of throwing an exception.

**Comment by JobJob** [comment]
Yeah, I think following what Distributions does makes sense, e.g. `pdf(DiscreteUniform(1,3), 4)` returns 0.0

Also, since there's an `@inbounds` on the line this throws, you need to make sure that index is ok regardless.

Cheers!

**Comment by oschulz** [comment]
Yep, will change that - thanks for your interest in the package!

**Comment by oschulz** [comment]
Hey @JobJob , sorry this took so long, should be fixed now. New version is getting registered right now.

**Comment by JobJob** [comment]
No probs, cheers!

**Comment by oschulz** [comment]
On the plus sides, everything should be type-stable now, and faster than before.
